version: "3.8"
services:
  db:
    image: postgres
    volumes: 
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=image_uploader_db
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
    container_name: postgres_db
  app-backend:
    build: .
    volumes:
      - .:/image-uploader
    ports:
      - 8000:8000
    image: app-backend:image-uploader
    container_name: drf_image_uploader
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: image_uploader_db
      DB_USER: testuser
      DB_PASSWORD: password
