# Generated by Django 4.1.7 on 2023-02-23 19:46

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0002_alter_user_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttier',
            name='description',
        ),
        migrations.AddField(
            model_name='accounttier',
            name='expiring_link_creation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounttier',
            name='link_to_original_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounttier',
            name='thumbnail_heights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=2, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
