# Generated by Django 4.1.7 on 2023-02-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0005_rename_link_to_original_access_accounttier_link_to_original_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttier',
            old_name='link_to_original_image',
            new_name='access_to_original_image',
        ),
    ]
